In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pyJHTDB

plt.rcParams.update(plt.rcParamsDefault)
#plt.rcParams['text.usetex'] = True
plt.rcParams['font.size'] = 12
plt.rcParams['font.family'] = "serif"

import matplotlib as mpl
mpl.rcParams['agg.path.chunksize'] = 100000

In [4]:
def rotmat(theta, phi):
    m = np.zeros((3, 3))
    m[0, 0] = np.sin(theta) * np.cos(phi)
    m[0, 1] = np.sin(theta) * np.sin(phi)
    m[0, 2] = np.cos(theta)
    m[1, 0] = np.cos(theta) * np.cos(phi)
    m[1, 1] = np.cos(theta) * np.sin(phi)
    m[1, 2] = -np.sin(theta)
    m[2, 0] = -np.sin(phi)
    m[2, 1] = np.cos(phi)
    m[2, 2] = 0.
    return m

In [5]:
x = np.array([1, 0, 0], dtype=np.float64)

In [17]:
np.matmul(x, rotmat(np.pi/2, np.pi/2))

array([6.123234e-17, 1.000000e+00, 6.123234e-17])

In [26]:
# get velocity at some point 

x0 = np.random.uniform(low = -1, high = 1, size = 3)

theta = np.random.uniform(low = 0, high = np.pi)
phi = np.random.uniform(low = 0, high = 2. * np.pi)

In [27]:
x0

array([-0.21221048, -0.60598094, -0.27217245])

In [25]:
width = np.array([0.1, 0.2, 0.3])

In [28]:
x1 = x0 + np.matmul(width[0] * np.array([1., 0., 0.]) , rotmat(theta, phi))

In [30]:
r = np.matmul(np.array([1,0,0]), rotmat(theta, phi))

In [31]:
r

array([ 0.51801164, -0.73987479, -0.42924264])

In [ ]:
np.array([1,0,0])

In [29]:
x1

array([-0.16040931, -0.67996842, -0.31509671])

In [33]:
np.matmul(np.array([0.2, 0, 0]), np.array([0.3, 0, 0]))

0.06